// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package module

import (
	"gorm.io/gorm"
	"okra_board2/controllers"
	"okra_board2/middlewares"
	"okra_board2/repositories"
	"okra_board2/services"
)

// Injectors from wire.go:

func InitAdminController(db *gorm.DB) controllers.AdminController {
	adminRepository := repositories.NewAdminRepositoryImpl(db)
	adminService := services.NewAdminServiceImpl(adminRepository)
	authRepository := repositories.NewAuthRepositoryImpl(db)
	authService := services.NewAuthServiceImpl(authRepository)
	adminController := controllers.NewAdminControllerImpl(adminService, authService)
	return adminController
}

func InitAuthMiddleware(db *gorm.DB) middlewares.AuthMiddleware {
	authRepository := repositories.NewAuthRepositoryImpl(db)
	authService := services.NewAuthServiceImpl(authRepository)
	authMiddleware := middlewares.NewAuthMiddlewareImpl(authService)
	return authMiddleware
}
